// Auto-generated by shelley.exe.dev/cmd/go2ts.go
// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts

// DO NOT EDIT. This file is automatically generated.

export interface Conversation {
	conversation_id: string;
	slug: string | null;
	user_initiated: boolean;
	created_at: string;
	updated_at: string;
	cwd: string | null;
	archived: boolean;
	parent_conversation_id: string | null;
	model: string | null;
}

export interface ConversationRuntime {
	conversation_id: string;
	working: boolean;
	active_job_id: string | null;
	last_event_id: number;
	current_model_id: string | null;
	updated_at: string;
}

export interface JobRun {
	job_id: string;
	conversation_id: string;
	parent_job_id: string | null;
	kind: string;
	status: string;
	trigger_message_id: string | null;
	model_id: string | null;
	timeout_seconds: number | null;
	input_json: string;
	output_json: string | null;
	error_json: string | null;
	attempt_count: number;
	created_at: string;
	started_at: string | null;
	finished_at: string | null;
}

export interface Usage {
	input_tokens: number;
	cache_creation_input_tokens: number;
	cache_read_input_tokens: number;
	output_tokens: number;
	reasoning_tokens?: number;
	cost_usd: number;
	model?: string;
	start_time?: string | null;
	end_time?: string | null;
}

export interface ApiMessageForTS {
	message_id: string;
	conversation_id: string;
	sequence_id: number;
	type: string;
	llm_data?: string | null;
	user_data?: string | null;
	usage_data?: string | null;
	created_at: string;
	display_data?: string | null;
	end_of_turn?: boolean | null;
}

export interface ConversationStateForTS {
	conversation_id: string;
	working: boolean;
	model?: string;
}

export interface NotificationEventForTS {
	type: EventType;
	conversation_id: string;
	timestamp: string;
	payload?: unknown;
}

export interface StreamResponseForTS {
	messages: ApiMessageForTS[] | null;
	conversation: Conversation;
	runtime?: ConversationRuntime | null;
	last_event_id?: number;
	conversation_state?: ConversationStateForTS | null;
	context_window_size?: number;
	heartbeat?: boolean;
	notification_event?: NotificationEventForTS | null;
	streaming_text?: string;
	streaming_thinking?: string;
}

export interface StreamEventEnvelopeForTS {
	version: number;
	event_id?: number;
	conversation_id: string;
	job_id?: string | null;
	type: string;
	created_at: string;
	payload?: unknown;
}

export interface ConversationWithStateForTS {
	conversation_id: string;
	slug: string | null;
	user_initiated: boolean;
	created_at: string;
	updated_at: string;
	cwd: string | null;
	archived: boolean;
	parent_conversation_id: string | null;
	model: string | null;
	working: boolean;
	git_repo_root?: string;
	git_worktree_root?: string;
	git_commit?: string;
	git_subject?: string;
	subagent_count: number;
}

export type MessageType = 'user' | 'agent' | 'tool' | 'error' | 'system' | 'gitinfo';

export type EventType = string;
