// A command line tool for generating typescript type declarations from go
// struct types.
//
// Example:
//
//	go run ./cmd/go2ts -o ui/src/generated-types.ts
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"go.skia.org/infra/go/go2ts"
	"shelley.exe.dev/db"
	"shelley.exe.dev/db/generated"
	"shelley.exe.dev/llm"
	"shelley.exe.dev/server/notifications"
)

func main() {
	outputPath := flag.String("o", "", "Path to the output TypeScript file.")
	flag.Parse()

	if *outputPath == "" {
		fmt.Println("Usage: go run ./cmd/go2ts -o <output-file>")
		os.Exit(1)
	}

	generator := TS()

	w, err := os.Create(*outputPath)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		os.Exit(1)
	}
	defer w.Close()

	fmt.Fprintf(w, "// Auto-generated by shelley.exe.dev/cmd/go2ts.go\n")
	fmt.Fprintf(w, "// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts\n\n")
	var rendered bytes.Buffer
	generator.Render(&rendered)
	output := strings.ReplaceAll(rendered.String(), ": any;", ": unknown;")
	fmt.Fprint(w, output)
}

// TS returns a Go2TS generator for go types we want to use in TypeScript.
func TS() *go2ts.Go2TS {
	generator := go2ts.New()

	// Database message types enum
	generator.AddMultipleUnion(
		[]db.MessageType{
			db.MessageTypeUser,
			db.MessageTypeAgent,
			db.MessageTypeTool,
			db.MessageTypeError,
			db.MessageTypeSystem,
			db.MessageTypeGitInfo,
		},
	)

	// Database struct types
	generator.AddMultiple(
		generated.Conversation{},
		generated.ConversationRuntime{},
		generated.JobRun{},
		llm.Usage{},
	)

	generator.AddMultiple(
		apiMessageForTS{},
		streamResponseForTS{},
		streamEventEnvelopeForTS{},
		conversationWithStateForTS{},
		notificationEventForTS{},
	)

	// Generate clean nominal types
	generator.GenerateNominalTypes = true

	return generator
}

type apiMessageForTS struct {
	MessageID      string    `json:"message_id"`
	ConversationID string    `json:"conversation_id"`
	SequenceID     int64     `json:"sequence_id"`
	Type           string    `json:"type"`
	LlmData        *string   `json:"llm_data,omitempty"`
	UserData       *string   `json:"user_data,omitempty"`
	UsageData      *string   `json:"usage_data,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	DisplayData    *string   `json:"display_data,omitempty"`
	EndOfTurn      *bool     `json:"end_of_turn,omitempty"`
}

type conversationStateForTS struct {
	ConversationID string `json:"conversation_id"`
	Working        bool   `json:"working"`
	Model          string `json:"model,omitempty"`
}

type conversationWithStateForTS struct {
	ConversationID       string  `json:"conversation_id"`
	Slug                 *string `json:"slug"`
	UserInitiated        bool    `json:"user_initiated"`
	CreatedAt            string  `json:"created_at"`
	UpdatedAt            string  `json:"updated_at"`
	Cwd                  *string `json:"cwd"`
	Archived             bool    `json:"archived"`
	ParentConversationID *string `json:"parent_conversation_id"`
	Model                *string `json:"model"`
	Working              bool    `json:"working"`
	GitRepoRoot          string  `json:"git_repo_root,omitempty"`
	GitWorktreeRoot      string  `json:"git_worktree_root,omitempty"`
	GitCommit            string  `json:"git_commit,omitempty"`
	GitSubject           string  `json:"git_subject,omitempty"`
	SubagentCount        int64   `json:"subagent_count"`
}

type streamResponseForTS struct {
	Messages          []apiMessageForTS              `json:"messages"`
	Conversation      generated.Conversation         `json:"conversation"`
	Runtime           *generated.ConversationRuntime `json:"runtime,omitempty"`
	LastEventID       int64                          `json:"last_event_id,omitempty"`
	ConversationState *conversationStateForTS        `json:"conversation_state,omitempty"`
	ContextWindowSize uint64                         `json:"context_window_size,omitempty"`
	Heartbeat         bool                           `json:"heartbeat,omitempty"`
	NotificationEvent *notificationEventForTS        `json:"notification_event,omitempty"`
	StreamingText     string                         `json:"streaming_text,omitempty"`
	StreamingThinking string                         `json:"streaming_thinking,omitempty"`
}

type streamEventEnvelopeForTS struct {
	Version        int     `json:"version"`
	EventID        int64   `json:"event_id,omitempty"`
	ConversationID string  `json:"conversation_id"`
	JobID          *string `json:"job_id,omitempty"`
	Type           string  `json:"type"`
	CreatedAt      string  `json:"created_at"`
	Payload        any     `json:"payload,omitempty"`
}

type notificationEventForTS struct {
	Type           notifications.EventType `json:"type"`
	ConversationID string                  `json:"conversation_id"`
	Timestamp      string                  `json:"timestamp"`
	Payload        any                     `json:"payload,omitempty"`
}
